// Original compile-input revision manifest implementation within the AGPL host boundary.
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { createHash } from 'node:crypto';

export interface CompileAuthority {
	readonly root: string;
	assertCurrent(): void | Promise<void>;
}

export interface CompileInputBarrierPoint {
	readonly kind: 'directory' | 'file';
	/** Workspace-relative path; an empty path identifies the workspace root. */
	readonly path: string;
	readonly signal?: AbortSignal;
}

export interface CompileInputLimits {
	readonly maxTreeDepth?: number;
	readonly maxTreeEntries?: number;
	readonly maxFileBytes?: number;
	readonly maxTotalBytes?: number;
	readonly barrier?: (point: CompileInputBarrierPoint) => void | Promise<void>;
	/** Main-process cancellation signal; never supplied by the renderer. */
	readonly signal?: AbortSignal;
}

export interface CompileInputEntry {
	readonly path: string;
	readonly dev: bigint;
	readonly ino: bigint;
	readonly size: bigint;
	readonly mtimeNs: bigint;
	readonly ctimeNs: bigint;
	readonly hash: string;
}

export interface CompileDirectoryEntry {
	readonly path: string;
	readonly dev: bigint;
	readonly ino: bigint;
}

export interface CompileInputDiff {
	readonly isStale: boolean;
	readonly added: readonly string[];
	readonly removed: readonly string[];
	readonly modifiedContent: readonly string[];
	readonly replacedIdentity: readonly string[];
	readonly directoriesChanged: readonly string[];
	readonly rootReplaced: boolean;
}

export interface CompileInputManifest {
	readonly root: string;
	readonly rootDev: bigint;
	readonly rootIno: bigint;
	readonly entries: readonly CompileInputEntry[];
	readonly directories: readonly CompileDirectoryEntry[];
	readonly totalBytes: bigint;
	readonly manifestRevision: string;
	assertCurrent(authority: CompileAuthority, limits?: CompileInputLimits): Promise<void>;
	isCurrent(authority: CompileAuthority, limits?: CompileInputLimits): Promise<boolean>;
}

export const DEFAULT_TREE_DEPTH_LIMIT = 16;
export const DEFAULT_TREE_ENTRY_LIMIT = 4096;
export const DEFAULT_FILE_BYTES_LIMIT = 32 * 1024 * 1024; // 32MB
export const DEFAULT_TOTAL_BYTES_LIMIT = 64 * 1024 * 1024; // 64MB

interface FileState {
	readonly dev: bigint;
	readonly ino: bigint;
	readonly size: bigint;
	readonly mtimeNs: bigint;
	readonly ctimeNs: bigint;
}

interface DirectoryState extends FileState {
	readonly path: string;
}

interface RootPathIdentity {
	readonly path: string;
	readonly dev: bigint;
	readonly ino: bigint;
}

// Keep ancestors out of the public manifest shape while including them in root comparisons.
const rootPathIdentities = new WeakMap<CompileInputManifest, readonly RootPathIdentity[]>();

function contained(root: string, candidate: string): boolean {
	const relative = path.relative(root, candidate);
	return relative === '' || (!path.isAbsolute(relative) && relative !== '..' && !relative.startsWith('..' + path.sep));
}

function isExcludedDirectory(name: string, parent: string): boolean {
	const lower = name.toLowerCase();
	// Only the fixed root output directory is generated by the managed compiler.
	return (!parent && lower === 'output') || lower === '.git' || lower === 'node_modules';
}

function assertSafeRelativeSegment(name: string): void {
	if (
		!name ||
		name === '.' ||
		name === '..' ||
		/[\\:\x00-\x1f\x7f]/.test(name) ||
		/[. ]$/.test(name) ||
		/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i.test(name)
	) {
		throw new Error('OUTSIDE_WORKSPACE');
	}
}

function sameNode(left: { dev: bigint; ino: bigint }, right: { dev: bigint; ino: bigint }): boolean {
	return left.dev === right.dev && left.ino === right.ino;
}

function sameFileState(left: FileState, right: FileState): boolean {
	return (
		left.dev === right.dev &&
		left.ino === right.ino &&
		left.size === right.size &&
		left.mtimeNs === right.mtimeNs &&
		left.ctimeNs === right.ctimeNs
	);
}

function asDirectoryState(target: string, stat: FileState): DirectoryState {
	return {
		path: target,
		dev: stat.dev,
		ino: stat.ino,
		size: stat.size,
		mtimeNs: stat.mtimeNs,
		ctimeNs: stat.ctimeNs
	};
}

function sameDirectoryVersion(left: DirectoryState, right: DirectoryState): boolean {
	return left.path === right.path && sameFileState(left, right);
}

function throwPathOperationError(error: unknown): never {
	const code = error && typeof error === 'object' ? (error as NodeJS.ErrnoException).code : undefined;
	if (code === 'ELOOP') throw new Error('LINK_NOT_ALLOWED');
	if (code === 'ENOENT' || code === 'ENOTDIR') throw new Error('STALE_WORKSPACE');
	throw error;
}

async function checkedPathOperation<T>(operation: Promise<T>): Promise<T> {
	try {
		return await operation;
	} catch (error) {
		return throwPathOperationError(error);
	}
}

function statPath(target: string) {
	return checkedPathOperation(fs.lstat(target, { bigint: true }));
}

function assertNotAborted(limits?: CompileInputLimits): void {
	if (limits?.signal?.aborted) throw new Error('CANCELLED');
}

async function barrierAt(
	limits: CompileInputLimits | undefined,
	kind: CompileInputBarrierPoint['kind'],
	relative: string
): Promise<void> {
	assertNotAborted(limits);
	if (limits?.barrier) {
		await Promise.resolve(limits.barrier({ kind, path: relative, signal: limits.signal }));
	}
	assertNotAborted(limits);
}

function boundedLimit(value: number | undefined, maximum: number): number {
	if (value === undefined) return maximum;
	if (!Number.isSafeInteger(value) || value < 0) throw new Error('INVALID_LIMIT');
	return Math.min(value, maximum);
}

async function inspectAbsoluteDirectoryChain(
	target: string,
	expected?: readonly DirectoryState[]
): Promise<DirectoryState[]> {
	const absolute = path.resolve(target);
	const parsed = path.parse(absolute);
	if (!parsed.root) throw new Error('STALE_WORKSPACE');

	const componentPaths = [parsed.root];
	let cursor = parsed.root;
	for (const part of absolute.slice(parsed.root.length).split(path.sep).filter(Boolean)) {
		cursor = path.join(cursor, part);
		componentPaths.push(cursor);
	}

	const states: DirectoryState[] = [];
	for (let index = 0; index < componentPaths.length; index++) {
		const componentPath = componentPaths[index]!;
		const stat = await statPath(componentPath);
		if (stat.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
		if (!stat.isDirectory()) throw new Error('STALE_WORKSPACE');
		const state = asDirectoryState(componentPath, stat);
		const prior = expected?.[index];
		if (prior && (prior.path !== state.path || !sameNode(prior, state))) {
			throw new Error('STALE_WORKSPACE');
		}
		states.push(state);
	}
	if (expected && expected.length !== states.length) throw new Error('STALE_WORKSPACE');
	return states;
}

async function checkedDirectoryPath(
	root: string,
	rootComponents: readonly DirectoryState[],
	capturedDirectories: ReadonlyMap<string, DirectoryState>,
	relative: string
): Promise<DirectoryState> {
	const components = await inspectAbsoluteDirectoryChain(root, rootComponents);
	let current = components[components.length - 1];
	const expectedRoot = capturedDirectories.get('');
	if (!current || !expectedRoot || !sameNode(current, expectedRoot)) throw new Error('STALE_WORKSPACE');

	let cursor = root;
	let prefix = '';
	for (const segment of relative ? relative.split('/') : []) {
		if (!segment || segment === '.' || segment === '..') throw new Error('STALE_WORKSPACE');
		cursor = path.join(cursor, segment);
		prefix = prefix ? `${prefix}/${segment}` : segment;
		const stat = await statPath(cursor);
		if (stat.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
		if (!stat.isDirectory()) throw new Error('STALE_WORKSPACE');
		current = asDirectoryState(cursor, stat);
		const expected = capturedDirectories.get(prefix);
		if (expected && !sameNode(current, expected)) throw new Error('STALE_WORKSPACE');
	}
	return current;
}

/**
 * Traverses the workspace root and builds an immutable manifest of local compile inputs.
 * Repeated path checks and held-descriptor comparisons detect observed replacements; they
 * are not an operating-system compare-and-swap.
 */
export async function captureCompileInputs(
	authority: CompileAuthority,
	limits?: CompileInputLimits
): Promise<CompileInputManifest> {
	if (!authority || typeof authority.root !== 'string' || !path.isAbsolute(authority.root)) {
		throw new Error('STALE_WORKSPACE');
	}

	const maxDepth = boundedLimit(limits?.maxTreeDepth, DEFAULT_TREE_DEPTH_LIMIT);
	const maxEntries = boundedLimit(limits?.maxTreeEntries, DEFAULT_TREE_ENTRY_LIMIT);
	const maxFileBytes = boundedLimit(limits?.maxFileBytes, DEFAULT_FILE_BYTES_LIMIT);
	const maxTotalBytes = boundedLimit(limits?.maxTotalBytes, DEFAULT_TOTAL_BYTES_LIMIT);
	const root = path.resolve(authority.root);

	assertNotAborted(limits);
	await Promise.resolve(authority.assertCurrent());
	const rootComponents = await inspectAbsoluteDirectoryChain(root);
	const rootState = rootComponents[rootComponents.length - 1];
	if (!rootState) throw new Error('STALE_WORKSPACE');
	const capturedDirectories = new Map<string, DirectoryState>([['', rootState]]);
	const walkedDirectories = new Map<string, DirectoryState>();
	const entries: CompileInputEntry[] = [];
	const directories: CompileDirectoryEntry[] = [
		Object.freeze({ path: '', dev: rootState.dev, ino: rootState.ino })
	];
	let inspected = 0;
	let totalBytes = 0n;

	await checkedDirectoryPath(root, rootComponents, capturedDirectories, '');
	const realRoot = await checkedPathOperation(fs.realpath(root));
	await checkedDirectoryPath(root, rootComponents, capturedDirectories, '');
	if (!contained(root, realRoot)) throw new Error('OUTSIDE_WORKSPACE');

	const walk = async (currentDir: string, currentPrefix: string, depth: number): Promise<void> => {
		assertNotAborted(limits);
		if (depth > maxDepth) throw new Error('TREE_TOO_DEEP');
		await Promise.resolve(authority.assertCurrent());
		await barrierAt(limits, 'directory', currentPrefix);

		const beforeOpen = await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
		const dir = await checkedPathOperation(fs.opendir(currentDir));
		try {
			const afterOpen = await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
			if (!sameDirectoryVersion(beforeOpen, afterOpen)) throw new Error('STALE_WORKSPACE');

			for await (const entry of dir) {
				assertNotAborted(limits);
				await Promise.resolve(authority.assertCurrent());
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				if (++inspected > maxEntries) throw new Error('TREE_TOO_LARGE');

				assertSafeRelativeSegment(entry.name);
				const relative = currentPrefix ? `${currentPrefix}/${entry.name}` : entry.name;
				const childPath = path.join(currentDir, entry.name);

				const initial = await statPath(childPath);
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				if (initial.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
				if (!initial.isDirectory() && !initial.isFile()) throw new Error('LINK_NOT_ALLOWED');

				const realChild = await checkedPathOperation(fs.realpath(childPath));
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				const child = await statPath(childPath);
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				if (child.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
				if (!child.isDirectory() && !child.isFile()) throw new Error('LINK_NOT_ALLOWED');
				if (!sameFileState(initial, child)) throw new Error('STALE_WORKSPACE');
				if (!contained(root, realChild)) throw new Error('OUTSIDE_WORKSPACE');

				// Exclusions are directory-only. The fixed root output directory is the
				// compiler artifact location; nested output directories are local inputs.
				if (child.isDirectory()) {
					if (isExcludedDirectory(entry.name, currentPrefix)) continue;
					if (capturedDirectories.has(relative)) throw new Error('STALE_WORKSPACE');
					capturedDirectories.set(relative, asDirectoryState(childPath, child));
					directories.push(Object.freeze({ path: relative, dev: child.dev, ino: child.ino }));
					await checkedDirectoryPath(root, rootComponents, capturedDirectories, relative);
					await walk(childPath, relative, depth + 1);
					continue;
				}

				if (child.size > BigInt(maxFileBytes)) throw new Error('FILE_TOO_LARGE');
				if (totalBytes + child.size > BigInt(maxTotalBytes)) throw new Error('FILE_TOO_LARGE');
				await barrierAt(limits, 'file', relative);
				await Promise.resolve(authority.assertCurrent());
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				const afterBarrier = await statPath(childPath);
				await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
				if (afterBarrier.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
				if (!afterBarrier.isFile() || !sameFileState(child, afterBarrier)) {
					throw new Error('STALE_WORKSPACE');
				}

				const handle = await checkedPathOperation(fs.open(childPath, 'r'));
				try {
					await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
					const before = await handle.stat({ bigint: true });
					if (!before.isFile()) throw new Error('STALE_WORKSPACE');
					if (before.size > BigInt(maxFileBytes) || totalBytes + before.size > BigInt(maxTotalBytes)) {
						throw new Error('FILE_TOO_LARGE');
					}
					const namedBefore = await statPath(childPath);
					await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
					if (namedBefore.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
					if (
						!namedBefore.isFile() ||
						!sameFileState(before, child) ||
						!sameFileState(namedBefore, before)
					) {
						throw new Error('STALE_WORKSPACE');
					}

					const buffer = new Uint8Array(Number(before.size));
					let offset = 0;
					while (offset < buffer.byteLength) {
						assertNotAborted(limits);
						const result = await handle.read(buffer, offset, buffer.byteLength - offset, offset);
						if (result.bytesRead === 0) throw new Error('STALE_WORKSPACE');
						offset += result.bytesRead;
					}

					const after = await handle.stat({ bigint: true });
					await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
					const current = await statPath(childPath);
					await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
					if (current.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
					if (!current.isFile() || !sameFileState(before, after) || !sameFileState(after, current)) {
						throw new Error('STALE_WORKSPACE');
					}

					await Promise.resolve(authority.assertCurrent());
					const hash = 'sha256:' + createHash('sha256').update(buffer).digest('hex');
					totalBytes += before.size;
					entries.push(
						Object.freeze({
							path: relative,
							dev: current.dev,
							ino: current.ino,
							size: current.size,
							mtimeNs: current.mtimeNs,
							ctimeNs: current.ctimeNs,
							hash
						})
					);
				} finally {
					await handle.close();
				}
			}

			const afterWalk = await checkedDirectoryPath(root, rootComponents, capturedDirectories, currentPrefix);
			if (!sameDirectoryVersion(beforeOpen, afterWalk)) throw new Error('STALE_WORKSPACE');
			walkedDirectories.set(currentPrefix, afterWalk);
		} finally {
			try {
				await dir.close();
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== 'ERR_DIR_CLOSED') throw error;
			}
		}
	};

	await walk(root, '', 0);

	// Recheck named file identities after traversal, then check directory versions after
	// those file checks so observed additions/removals cannot be silently omitted.
	for (const entry of entries) {
		assertNotAborted(limits);
		await Promise.resolve(authority.assertCurrent());
		const separator = entry.path.lastIndexOf('/');
		const parent = separator < 0 ? '' : entry.path.slice(0, separator);
		const filename = path.join(root, ...entry.path.split('/'));
		await checkedDirectoryPath(root, rootComponents, capturedDirectories, parent);
		const current = await statPath(filename);
		if (current.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
		const recorded: FileState = {
			dev: entry.dev,
			ino: entry.ino,
			size: entry.size,
			mtimeNs: entry.mtimeNs,
			ctimeNs: entry.ctimeNs
		};
		if (!current.isFile() || !sameFileState(current, recorded)) throw new Error('STALE_WORKSPACE');
		const realPath = await checkedPathOperation(fs.realpath(filename));
		await checkedDirectoryPath(root, rootComponents, capturedDirectories, parent);
		const afterRealpath = await statPath(filename);
		if (afterRealpath.isSymbolicLink()) throw new Error('LINK_NOT_ALLOWED');
		if (!contained(root, realPath)) throw new Error('OUTSIDE_WORKSPACE');
		if (!afterRealpath.isFile() || !sameFileState(current, afterRealpath)) {
			throw new Error('STALE_WORKSPACE');
		}
	}

	const finalDirectories = [...capturedDirectories.keys()].sort(
		(a, b) => a.split('/').length - b.split('/').length || a.localeCompare(b)
	);
	for (const relative of finalDirectories) {
		assertNotAborted(limits);
		await Promise.resolve(authority.assertCurrent());
		const current = await checkedDirectoryPath(root, rootComponents, capturedDirectories, relative);
		const walked = walkedDirectories.get(relative);
		if (!walked || !sameDirectoryVersion(current, walked)) throw new Error('STALE_WORKSPACE');
	}
	assertNotAborted(limits);
	await Promise.resolve(authority.assertCurrent());

	entries.sort((a, b) => a.path.localeCompare(b.path));
	directories.sort((a, b) => a.path.localeCompare(b.path));

	const hasher = createHash('sha256');
	for (const component of rootComponents) {
		hasher.update(`root-path:${component.path}:${component.dev}:${component.ino}\n`);
	}
	hasher.update(`root:${rootState.dev}:${rootState.ino}\n`);
	for (const dir of directories) {
		hasher.update(`dir:${dir.path}:${dir.dev}:${dir.ino}\n`);
	}
	for (const entry of entries) {
		hasher.update(
			`file:${entry.path}:${entry.dev}:${entry.ino}:${entry.size}:${entry.mtimeNs}:${entry.ctimeNs}:${entry.hash}\n`
		);
	}
	const manifestRevision = 'sha256:' + hasher.digest('hex');

	const manifest: CompileInputManifest = {
		root: authority.root,
		rootDev: rootState.dev,
		rootIno: rootState.ino,
		entries: Object.freeze(entries),
		directories: Object.freeze(directories),
		totalBytes,
		manifestRevision,
		assertCurrent: (auth, lim) => assertCompileInputsCurrent(auth, manifest, lim),
		isCurrent: (auth, lim) => checkCompileInputsCurrent(auth, manifest, lim)
	};
	const immutableManifest = Object.freeze(manifest);
	rootPathIdentities.set(
		immutableManifest,
		Object.freeze(
			rootComponents.map((component) =>
				Object.freeze({ path: component.path, dev: component.dev, ino: component.ino })
			)
		)
	);
	return immutableManifest;
}

/**
 * Compares two input manifests for additions, removals, content changes,
 * directory/root replacements, or same-byte identity replacements.
 */
export function compareCompileInputManifests(
	before: CompileInputManifest,
	after: CompileInputManifest
): CompileInputDiff {
	const beforeRootPath = rootPathIdentities.get(before);
	const afterRootPath = rootPathIdentities.get(after);
	const rootPathReplaced =
		beforeRootPath === undefined || afterRootPath === undefined
			? beforeRootPath !== afterRootPath
			: beforeRootPath.length !== afterRootPath.length ||
				beforeRootPath.some(
					(component, index) =>
						component.path !== afterRootPath[index]?.path ||
						component.dev !== afterRootPath[index]?.dev ||
						component.ino !== afterRootPath[index]?.ino
				);
	const rootReplaced =
		path.resolve(before.root) !== path.resolve(after.root) ||
		before.rootDev !== after.rootDev ||
		before.rootIno !== after.rootIno ||
		rootPathReplaced;

	const beforeEntries = new Map<string, CompileInputEntry>();
	for (const e of before.entries) beforeEntries.set(e.path, e);
	const afterEntries = new Map<string, CompileInputEntry>();
	for (const e of after.entries) afterEntries.set(e.path, e);

	const added: string[] = [];
	const removed: string[] = [];
	const modifiedContent: string[] = [];
	const replacedIdentity: string[] = [];
	for (const [entryPath, afterEntry] of afterEntries) {
		const beforeEntry = beforeEntries.get(entryPath);
		if (!beforeEntry) added.push(entryPath);
		else if (beforeEntry.hash !== afterEntry.hash) modifiedContent.push(entryPath);
		else if (
			beforeEntry.dev !== afterEntry.dev ||
			beforeEntry.ino !== afterEntry.ino ||
			beforeEntry.mtimeNs !== afterEntry.mtimeNs ||
			beforeEntry.ctimeNs !== afterEntry.ctimeNs ||
			beforeEntry.size !== afterEntry.size
		) {
			replacedIdentity.push(entryPath);
		}
	}
	for (const entryPath of beforeEntries.keys()) {
		if (!afterEntries.has(entryPath)) removed.push(entryPath);
	}

	const beforeDirs = new Map<string, CompileDirectoryEntry>();
	for (const d of before.directories) beforeDirs.set(d.path, d);
	const afterDirs = new Map<string, CompileDirectoryEntry>();
	for (const d of after.directories) afterDirs.set(d.path, d);
	const directoriesChanged: string[] = [];
	for (const [dirPath, afterDir] of afterDirs) {
		const beforeDir = beforeDirs.get(dirPath);
		if (!beforeDir || beforeDir.dev !== afterDir.dev || beforeDir.ino !== afterDir.ino) {
			directoriesChanged.push(dirPath);
		}
	}
	for (const dirPath of beforeDirs.keys()) {
		if (!afterDirs.has(dirPath)) directoriesChanged.push(dirPath);
	}

	const isStale =
		rootReplaced ||
		added.length > 0 ||
		removed.length > 0 ||
		modifiedContent.length > 0 ||
		replacedIdentity.length > 0 ||
		directoriesChanged.length > 0;
	return Object.freeze({
		isStale,
		added: Object.freeze(added.sort((a, b) => a.localeCompare(b))),
		removed: Object.freeze(removed.sort((a, b) => a.localeCompare(b))),
		modifiedContent: Object.freeze(modifiedContent.sort((a, b) => a.localeCompare(b))),
		replacedIdentity: Object.freeze(replacedIdentity.sort((a, b) => a.localeCompare(b))),
		directoriesChanged: Object.freeze(directoriesChanged.sort((a, b) => a.localeCompare(b))),
		rootReplaced
	});
}

/** Asserts that the filesystem compile inputs still match the captured manifest. */
export async function assertCompileInputsCurrent(
	authority: CompileAuthority,
	manifest: CompileInputManifest,
	limits?: CompileInputLimits
): Promise<void> {
	assertNotAborted(limits);
	await Promise.resolve(authority.assertCurrent());
	if (path.resolve(authority.root) !== path.resolve(manifest.root)) throw new Error('STALE_WORKSPACE');
	const current = await captureCompileInputs(authority, limits);
	if (compareCompileInputManifests(manifest, current).isStale) throw new Error('STALE_WORKSPACE');
	assertNotAborted(limits);
	await Promise.resolve(authority.assertCurrent());
}

/** Checks whether the filesystem compile inputs under authority are currently valid and unmodified. */
export async function checkCompileInputsCurrent(
	authority: CompileAuthority,
	manifest: CompileInputManifest,
	limits?: CompileInputLimits
): Promise<boolean> {
	try {
		await assertCompileInputsCurrent(authority, manifest, limits);
		return true;
	} catch {
		return false;
	}
}
