import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import { includeIgnoreFile } from '@eslint/compat';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import { fileURLToPath } from 'node:url';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default ts.config(
	includeIgnoreFile(gitignorePath),
	// vendored pdf.js modules keep upstream style (see src/lib/draft/type1/README.md)
	{ ignores: ['src/lib/draft/type1/*.js'] },
	// generated by the Paraglide compiler (paraglideVitePlugin in vite.config.ts), never hand-edited
	{ ignores: ['src/lib/paraglide/**'] },
	js.configs.recommended,
	...ts.configs.recommended,
	// eslint-plugin-svelte: flat-config presets live under 'flat/*'; 'recommended' is the
	// legacy-eslintrc object and is not spreadable
	...svelte.configs['flat/recommended'],
	prettier,
	...svelte.configs['flat/prettier'],
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			'no-undef': 'off',
			// Arrived with eslint 10 / eslint-plugin-svelte 3, all firing on code that predates
			// them: 73 hits across the app. Warnings rather than errors, so the upgrade does not
			// hide behind a mass rewrite - prefer-svelte-reactivity in particular swaps plain
			// Map/Set for reactive ones, which is a runtime change and wants its own pass.
			'svelte/prefer-svelte-reactivity': 'warn',
			'svelte/require-each-key': 'warn',
			'svelte/no-unused-props': 'warn',
			'svelte/no-useless-mustaches': 'warn',
			'svelte/no-dom-manipulating': 'warn',
			'no-useless-assignment': 'warn',
			'preserve-caught-error': 'warn',
			// underscore prefix = intentionally unused
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_'
				}
			]
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	}
);
