import type { HelpTopic } from '../features/help/topics.ts';
/** Original instructions; license and installation documents remain unmodified source material. */
export const helpTitles: Readonly<Record<HelpTopic, string>> = Object.freeze({
	'getting-started': 'Getting started', editing: 'Editing documents', 'tables-math': 'Tables and equations', compilation: 'PDF compilation', shortcuts: 'Shortcuts', installation: '0.1.0 installation guide', licenses: 'License scope', agpl: 'AGPL full text', apache: 'Apache full text', notices: 'Third-party notices'
});
export const helpEnglish: Readonly<Partial<Record<HelpTopic, string>>> = Object.freeze({
	'getting-started': '## Open a document\nChoose Open document to select a UTF-8 TeX file. The desktop app can also open a folder; select its files in the sidebar.\n## Save and preview\nThe desktop app saves documents and compiles PDFs. A browser file picker does not grant permission to write back to disk.\nSave changes you want to keep before opening another document. Unsaved changes require confirmation before switching.',
	editing: '## Choose a mode\n- Source: edit LaTeX directly, with section and environment folding.\n- Visual: edit recognized text, formatting and inline equations. Unknown syntax stays as Raw LaTeX.\n- Split: show source and visual content together; both share the same document and undo history.\n## Navigate sections\nSelect Outline in the sidebar, then choose a section. If parsing stops, source editing remains available; Reparse restores the outline and visual content.\n## Preserve unknown syntax\nUse Edit source on a Raw LaTeX block, or switch to Source mode. Unsupported visual edits never overwrite the original content.',
	'tables-math': '## Tables\nChoose Table in Source, Visual or Split mode. A three-line table uses equal-width hline rules without a package, or Booktabs with an explicit preamble preview and confirmation. Full-border and horizontal-rule styles are also available. Set the header row, caption position, table width and relative column widths.\nGenerated tables can be reopened from the visual edit button or Edit table at cursor in source mode. Unknown column specifications and custom macros stay editable in source mode.\nDeleting nonempty rows or columns requires confirmation. Closing the panel keeps its draft for the current document.\n## Equations and matrices\nEquation and Matrix open panels inside the editor. Matrices support 1–10 rows and columns, including square dimensions. Shrinking away nonempty cells requires confirmation.\nMatrices use base-LaTeX array syntax without silently adding packages.',
	compilation: '## Compile a PDF\nOpen a TeX document in the desktop app and choose Compile PDF. Changes are saved first. If the disk file changed externally, compilation stops rather than overwriting it.\nManaged Tectonic downloads missing resources from fixed official sources. First compilation and new packages may need a network connection; subsequent runs use the local cache.\n## Errors and cancellation\n- Failure or cancellation preserves the last successful PDF.\n- Errors with an explicit entry filename and line number provide Go to source. Navigation is disabled when the document version changes.\n- For other errors, open TeX compile log.\n- After editing, the preview indicates that it belongs to an earlier compilation.\n- Cancel compilation waits for the engine to finish; resource release is not instantaneous.',
	shortcuts: '## Documents\n- Ctrl / Command + O: open a TeX document.\n- Ctrl / Command + S: save the current desktop document.\n- Ctrl / Command + Enter: compile the workbench document. Settings can change this to Ctrl / Command + Shift + B, or disable it.\n## Editor\n- Ctrl / Command + Z: undo.\n- Ctrl / Command + Shift + Z: redo.\n- Ctrl / Command + Y: redo.\n- Ctrl / Command + B, I or U: bold, italic or underline.\n- Escape: close the current tool panel without applying changes.\nUse Tab to reach toolbar controls and Enter or Space to activate them.',
	licenses: '## Desktop application\nModuTeX is derived from Texpile. The desktop application and existing Electron host remain AGPL-3.0-only. Rewriting the frontend does not automatically change the license of the combined application.\n## New frontend\nThe new renderer and source core have not completed independent provenance and license review. No claim is made that the entire application is Apache-2.0.\n## Apache exceptions\nThe existing Apache-2.0 exceptions cover only scripts/vendor/vendor-manifest.mjs and scripts/vendor/vendor-manifest.test.mjs, not other code or assets.\n## Third parties\nComponents retain their own licenses. Read Third-party notices and the notices included with the distribution.'
});
