// wasm-pack drops a `.gitignore` containing `*` into its output directory, on the assumption that
// the build artifacts are regenerated by whoever consumes them. Ours are committed on purpose, so
// that a normal `npm ci` needs no Rust toolchain — leaving that file in place would silently
// exclude the wasm from every commit, and the failure only shows up on a clean checkout.
import { rm, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'pkg');

await rm(join(pkgDir, '.gitignore'), { force: true });

// fail loudly if the artifact the app imports is missing, rather than leaving a stale one in place
const wasm = join(pkgDir, 'texpile_typst_syntax_wasm_bg.wasm');
const { size } = await stat(wasm).catch(() => {
	throw new Error(`postbuild: ${wasm} was not produced`);
});
console.log(`postbuild: pkg/ ready (${(size / 1024).toFixed(0)} KB wasm)`);
